name: lnpay-build-test-workflow
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: bash docker.sh build
      - name: Build codecept
        run: docker exec lnpay-php vendor/bin/codecept build
      - name: Build polar
        run: bash docker.sh polarup
      - name: Run unit tests
        run: docker exec lnpay-php vendor/bin/codecept run unit
      - name: Run api tests
        run: docker exec lnpay-php vendor/bin/codecept run api
